/**
 * The Walmart service name headers.
 */
export interface WM_SVC {
  /**
   * Walmart Service Name
   * @example Walmart Gateway API
   */
  NAME: string;
}

/**
 * Walmart QOS headers.
 */
export interface WM_QOS {
  /**
   * A unique ID to correlate a vendor's calls with the Walmart system.
   * @example 1234hfvgtr
   */
  CORRELATION_ID: string;
}

/**
 * Walmart security headers.
 */
export interface WM_SEC {
  /**
   * The Epoch timestamp.
   * @example 1443748249449
   */
  TIMESTAMP: number;
  /**
   * The vendor's digital signature, generated by running the JAR file or custom
   * generation code.
   * @example 9fg3TPeRt0WSGbXNGGj4kSQ9L6PMBX/q+ovdy9bDQfvdhYs8NoEsjRX4fD7UNIHTddg...
   */
  AUTH_SIGNATURE: string;
}

/**
 * Walmart consumer channel headers.
 */
export interface CHANNEL {
  /**
   * A unique ID to track the consumer request by channel. Use the Consumer Channel
   * Type received during onboarding.
   * @example 0f3e4dd4-0514-4346-b39d-...
   */
  TYPE: string;
}

/**
 * Walmart consumer headers.
 */
export interface WM_CONSUMER {
  /**
   * Walmart consumer channel headers.
   */
  CHANNEL: CHANNEL;
  /**
   * The Walmart Consumer ID from Developer Center required to access the API.
   */
  ID: string;
}

/**
 * Walmart authentication hedaers.
 */
export class Headers {
  /**
   * The Walmart service name headers.
   */
  WM_SVC: WM_SVC = {
    NAME: 'Walmart Marketplace'
  };
  /**
   * Walmart QOS headers.
   */
  WM_QOS: WM_QOS;
  /**
   * Walmart security headers.
   */
  WM_SEC: WM_SEC;
  /**
   * Walmart consumer headers.
   */
  WM_CONSUMER: WM_CONSUMER;
  /**
   * The returned data format in the response.
   */
  Accept: string = 'application/json';
  /**
   * The data format used in the request;
   */
  'Content-Type': string = 'application/json';
}
